INSERT INTO movie (name, original_name, slug, age_restrictions, short_description, year, duration) VALUES
('ТОЧКА ЗІТКНЕННЯ', 'Sharp Corner', 'sharp-corner-uk', 'A16', 'Опис відсутній.', 2024, 6600),
('ОДНЕ ЦІЛЕ', 'Together', 'together-uk', 'A16', 'Опис відсутній.', 2025, 6120),
('ЕДДІНГТОН', 'Eddington', 'eddington-uk', 'A16', 'Опис відсутній.', 2025, 7200),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «ФІНІКІЙСЬКА СХЕМА»', 'The Phoenician Scheme', 'pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'A16', 'Голова сімейства вирішує передати родинний бізнес єдиній донці – нова пригода від легендарного режисера Веса Андерсона', 2025, 7860),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «ТІНІ ЗАБУТИХ ПРЕДКІВ (ВІДРЕСТАВРОВАНА ВЕРСІЯ)»', 'Тіні забутих предків', 'pokaz-iz-lekcieu-shadows-of-forgotten-uk', 'A0', 'Фільм не лише розповідає про любов і трагедію, але й показує неповторну культуру та природу України', 2025, 7680),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «НЕПРИСТОЙНА ПРОПОЗИЦІЯ»', 'Being Maria', 'pokaz-iz-lekcieu-being-maria-uk', 'A18', 'Заради переконливих емоцій у кадрі юну акторку Марію не попереджають про те, що зніматимуть сцену зґвалтування.', 2024, 7800),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «ВИКРАДЕНИЙ»', 'Rapito', 'pokaz-iz-lekcieu-vikradenii', 'A16', 'Опис відсутній.', 2023, 9840),
('ATEEZ WORLD TOUR [TOWARDS THE LIGHT: WILL TO POWER] IN SEOUL', 'Ateez World Tour [Towards the Light: Will to Power] in Seoul', 'ateez-world-tour-towards-the-light-will-to-power-in-seoul-uk', 'A12', 'Неймовірні виступи і вибухова енергія ATEEZ на сцені у фільмі-концерті ATEEZ WORLD TOUR світом так, як ніколи раніше', 2025, 7560),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «СЕРФЕР»', 'The Surfer', 'pokaz-iz-lekcieu-the-surfer-2024-uk', 'A16', 'На цьому пляжі не раді туристам. Спроби боротися з цим твердженням доводять Серфера до втрати людської подоби.', 2024, 7980),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «BATMAN» (МОВОЮ ОРИГІНАЛУ) 1989', 'Batman', 'pokaz-iz-lekcieu-batman-1989-uk', 'A12', 'Відзначаючи тридцяту річницю з дати виходу культової стрічки, ми покажемо одну з найпопулярніших історій про Бетмена на великому екрані.', 1989, 9360),
('ПОСПІШАЙ У ЗАВТРА', 'Hurry Up Tomorrow', 'hurry-up-tomorrow-uk', 'A16', 'Психологічний трилер про музиканта, який страждає від безсоння і вирушає в одіссею, що кидає виклик його існуванню', 2025, 6300),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «МІСІЯ НЕМОЖЛИВА: ФІНАЛЬНА РОЗПЛАТА»', 'Mission: Impossible - The Final Reckoning', 'pokaz-iz-lekcieu-mission-impossible-the-final-reckoning-uk', 'A16', 'Найкращий агент таємної служби отримує чергове завдання, найскладніше за всю його кар’єру.', 2025, 11940),
('ДОПРЕМ’ЄРНИЙ ПОКАЗ «ПУНКТ ПРИЗНАЧЕННЯ: РОДОВЕ ПРОКЛЯТТЯ»', 'Final Destination: Bloodlines', 'pre-premiere-final-destination-bloodlines-uk', 'A18', 'Повернення легендарної франшизи, герої якої відчайдушно намагатимуться уникнути смерті.', 2025, 6600),
('ДОПРЕМ’ЄРНИЙ ПОКАЗ «МІСІЯ НЕМОЖЛИВА: ФІНАЛЬНА РОЗПЛАТА»', 'Mission: Impossible - The Final Reckoning', 'pre-premiere-mission-impossible-the-final-reckoning-uk', 'A16', 'Найкращий агент таємної служби отримує чергове завдання, найскладніше за всю його кар’єру.', 2025, 10140),
('ХАГЕН - У ДОЛИНІ НІБЕЛУНГІВ', 'Hagen - Im Tal der Nibelungen', 'hagen-uk', 'A18', 'Опис відсутній.', 2024, 8340),
('ВИПАДКОВІ СВІДКИ', 'Alarum', 'alarum-uk', 'A18', 'Опис відсутній.', 2025, 5700),
('КРИВАВИЙ ЛІДЕР', 'The Order', 'the-order-2024-uk', 'A18', 'Опис відсутній.', 2024, 6960),
('МЕДОВИЙ МІСЯЦЬ БЕЗ НАРЕЧЕНОГО', 'Falling in Love in Niagara', 'falling-in-love-in-niagara-uk', 'A16', 'Опис відсутній.', 2024, 5040),
('БРОНЯ', 'Armor', 'armor-uk', 'A18', 'Опис відсутній.', 2024, 5340),
('ЛЮБІ ПРЕКРАСНІ КОХАНІ', 'Dear Beautiful Beloved', 'dear-beautiful-beloved-uk', 'A16', '13-й Тиждень австрійського кіно', 2024, 5580),
('ЯК БУТИ НОРМАЛЬНИМ І ХИМЕРНОСТІ ІНШОГО СВІТУ', 'How to Be Normal and the Oddness of the Other World', 'how-to-be-normal-and-the-oddness-of-the-other-world-uk', 'A16', '13-й Тиждень австрійського кіно', 2025, 6120),
('ТУШКОВАНА СВИНИНА', 'Pulled Pork', 'pulled-pork-uk', 'A16', '13-й Тиждень австрійського кіно', 2023, 7140),
('ПАВИЧ', 'Pfau - Bin ich echt?', 'peacock-2024-uk', 'A16', '13-й Тиждень австрійського кіно', 2024, 6120),
('ВИКРАДЕНИЙ', 'Rapito', 'vikradenii', 'A16', 'Опис відсутній.', 2023, 8040),
('СПОКУТА ГРІХІВ', 'Absolution', 'absolution-uk', 'A18', 'Коли приходить час платити по рахункам', 2024, 6720),
('ПОКАЗ ІЗ ЛЕКЦІЄЮ «БАЛКОНЕТКИ»', 'Les Femmes au balcon', 'pokaz-iz-lekcieu-les-femmes-au-balcon-uk', 'A18', 'Моторошні пригоди трьох подруг, які багато часу проводять на балконі своєї квартири, спостерігаючи за сусідами', 2024, 8040),
('КВІТИ УКРАЇНИ', 'Flowers of Ukraine', 'kwity-ukrainy', 'A0', 'Сила спротиву однієї жінки проти забудовників', 2024, 4200),
('ДОПРЕМ’ЄРНИЙ ПОКАЗ «ДВІ СЕСТРИ»', 'Дві сестри', 'pre-premiere-dwie-siostry-uk', 'A16', 'ЩОБ ПРИДБАТИ КВИТОК ОБЕРИ КІНОТЕАТР У БЛОКБАСТЕР', 2025, 9480),
('СПЕЦІАЛЬНИЙ ПОКАЗ «ОЧІ: ЛЕГЕНДА КАРПАТ»', 'The Legend of Ochi', 'special-show-the-legend-of-ochi-uk', 'A0', 'ЩОБ ПРИДБАТИ КВИТОК ОБЕРИ КІНОТЕАТР У RIVER MALL', 2025, 7800),
('ДОПРЕМ’ЄРНИЙ ПОКАЗ «UNTIL DAWN: ДО СВІТАНКУ»', 'Until Dawn', 'pre-premiere-until-dawn-2025-uk', 'A18', 'Друзі вирішили заночувати у місцевості, де рік тому загадково зникла дівчина. Схоже, тепер ця ж доля спіткає і їх.', 2025, 6180),
('МІСІЯ НЕМОЖЛИВА: РОЗПЛАТА. ЧАСТИНА ПЕРША', 'Mission: Impossible - Dead Reckoning Part One', 'mission-impossible-dead-reckoning-part-one-uk', 'A16', 'Ітан Хант на чолі групи оперативників, береться за справу. Цього разу їм знову доведеться, ризикуючи життям, рятувати світ від халепи.', 2023, 9780),
('СИВОЧОЛІ ГРАВЦІ', 'Silver Servers', 'silver-servers-uk', 'A0', 'Історія чотирьох «супердосвідчених» тенісистів, серед яких найстарший гравець у світі - українець Леонід', 2024, 6180),
('ВЕЛИКИЙ УТІКАЧ', 'The Great Escaper', 'the-great-escaper-uk', 'A12', 'Ветеран тікає з дому для літніх людей, щоб потрапити на річницю дня висадки в Нормандії', 2023, 5760),
('ПРИПУТНІ', 'Припутні', 'priputni-uk', 'A16', 'Донька, матір та їхній таксист прямують у глухе село, і ця поїздка усім вилізе боком', 2017, 5760),
('ПАРИЖ, 13-Й ОКРУГ', 'Les Olympiades', 'paris-13th-district-uk', 'A0', 'Прониклива історія з життя паризьких міленіалів', 2021, 6360),
('БЕРЛІН АЛЕКСАНДЕРПЛАЦ', 'Berlin Alexanderplatz', 'berlin-alexanderplatz-uk', 'A12', 'Мігрант з Африки занурюється у кримінальний світ Німеччини', 2020, 11040),
('ДІВЧАТА', 'Tytöt tytöt tytöt', 'girl-picture-uk', 'A16', 'Фінська драма про дорослішання, кохання та дружбу', 2022, 6120),
('ВЕЛИКА СВОБОДА', 'Große Freiheit', 'grosse-freiheit-uk', 'A16', 'Історія ув’язненого за гомосексуальність Ганса, який бореться зі своєю сексуальністю та системою у післявоєнній Німеччині', 2021, 6960);

INSERT INTO genre (slug, name) VALUES
('fcjmy', 'Вестерн'),
('6yl3z', 'Детективне');

INSERT INTO movie_category (movie_id, category_id) VALUES
('sharp-corner-uk', 'yevropejske'),
('together-uk', 'golivudske'),
('eddington-uk', 'golivudske'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'yevropejske'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'golivudske'),
('pokaz-iz-lekcieu-shadows-of-forgotten-uk', 'ukrayinske'),
('pokaz-iz-lekcieu-being-maria-uk', 'yevropejske'),
('pokaz-iz-lekcieu-vikradenii', 'yevropejske'),
('ateez-world-tour-towards-the-light-will-to-power-in-seoul-uk', 'azijske'),
('ateez-world-tour-towards-the-light-will-to-power-in-seoul-uk', 'a402k'),
('pokaz-iz-lekcieu-the-surfer-2024-uk', 'yevropejske'),
('pokaz-iz-lekcieu-the-surfer-2024-uk', 'golivudske'),
('pokaz-iz-lekcieu-batman-1989-uk', 'klasika'),
('pokaz-iz-lekcieu-batman-1989-uk', 'golivudske'),
('hurry-up-tomorrow-uk', 'golivudske'),
('pokaz-iz-lekcieu-mission-impossible-the-final-reckoning-uk', 'blokbaster'),
('pokaz-iz-lekcieu-mission-impossible-the-final-reckoning-uk', 'golivudske'),
('pre-premiere-final-destination-bloodlines-uk', 'golivudske'),
('pre-premiere-mission-impossible-the-final-reckoning-uk', 'blokbaster'),
('pre-premiere-mission-impossible-the-final-reckoning-uk', 'golivudske'),
('hagen-uk', 'yevropejske'),
('alarum-uk', 'golivudske'),
('the-order-2024-uk', 'yevropejske'),
('the-order-2024-uk', 'golivudske'),
('falling-in-love-in-niagara-uk', 'golivudske'),
('armor-uk', 'golivudske'),
('dear-beautiful-beloved-uk', 'yevropejske'),
('dear-beautiful-beloved-uk', 'festivalne'),
('how-to-be-normal-and-the-oddness-of-the-other-world-uk', 'yevropejske'),
('how-to-be-normal-and-the-oddness-of-the-other-world-uk', 'festivalne'),
('pulled-pork-uk', 'yevropejske'),
('pulled-pork-uk', 'festivalne'),
('peacock-2024-uk', 'yevropejske'),
('peacock-2024-uk', 'festivalne'),
('vikradenii', 'yevropejske'),
('absolution-uk', 'golivudske'),
('pokaz-iz-lekcieu-les-femmes-au-balcon-uk', 'yevropejske'),
('kwity-ukrainy', 'yevropejske'),
('kwity-ukrainy', 'ukrayinske'),
('pre-premiere-dwie-siostry-uk', 'ukrayinske'),
('special-show-the-legend-of-ochi-uk', 'rozvazhal-nie'),
('pre-premiere-until-dawn-2025-uk', 'golivudske'),
('mission-impossible-dead-reckoning-part-one-uk', 'blokbaster'),
('mission-impossible-dead-reckoning-part-one-uk', 'golivudske'),
('silver-servers-uk', 'yevropejske'),
('silver-servers-uk', 'festivalne'),
('the-great-escaper-uk', 'yevropejske'),
('priputni-uk', 'rozvazhal-nie'),
('priputni-uk', 'avtorske'),
('priputni-uk', 'ukrayinske'),
('paris-13th-district-uk', 'avtorske'),
('paris-13th-district-uk', 'yevropejske'),
('berlin-alexanderplatz-uk', 'yevropejske'),
('berlin-alexanderplatz-uk', 'festivalne'),
('girl-picture-uk', 'yevropejske'),
('girl-picture-uk', 'festivalne'),
('grosse-freiheit-uk', 'yevropejske'),
('grosse-freiheit-uk', 'festivalne');

INSERT INTO movie_genre (movie_id, genre_id) VALUES
('sharp-corner-uk', '9yhho'),
('together-uk', '9yhho'),
('together-uk', 'yqd7x'),
('eddington-uk', 'uklbv'),
('eddington-uk', 'fcjmy'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'kriminalne'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', '9yhho'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'w2923'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'hvtsf'),
('pokaz-iz-lekcieu-the-phoenician-scheme-uk', 'uklbv'),
('pokaz-iz-lekcieu-shadows-of-forgotten-uk', 'a3219'),
('pokaz-iz-lekcieu-being-maria-uk', 'a3219'),
('pokaz-iz-lekcieu-vikradenii', 'istorichne'),
('pokaz-iz-lekcieu-vikradenii', 'a3219'),
('ateez-world-tour-towards-the-light-will-to-power-in-seoul-uk', 'koncert'),
('pokaz-iz-lekcieu-the-surfer-2024-uk', '9yhho'),
('pokaz-iz-lekcieu-batman-1989-uk', 'w2923'),
('pokaz-iz-lekcieu-batman-1989-uk', 'q9wdt'),
('hurry-up-tomorrow-uk', '9yhho'),
('pokaz-iz-lekcieu-mission-impossible-the-final-reckoning-uk', '9yhho'),
('pokaz-iz-lekcieu-mission-impossible-the-final-reckoning-uk', 'w2923'),
('pokaz-iz-lekcieu-mission-impossible-the-final-reckoning-uk', 'hvtsf'),
('pre-premiere-final-destination-bloodlines-uk', 'c065f'),
('pre-premiere-mission-impossible-the-final-reckoning-uk', '9yhho'),
('pre-premiere-mission-impossible-the-final-reckoning-uk', 'w2923'),
('pre-premiere-mission-impossible-the-final-reckoning-uk', 'hvtsf'),
('hagen-uk', 'w2923'),
('hagen-uk', 'hvtsf'),
('hagen-uk', 'hponb'),
('alarum-uk', 'kriminalne'),
('alarum-uk', '9yhho'),
('alarum-uk', 'hvtsf'),
('the-order-2024-uk', 'kriminalne'),
('the-order-2024-uk', '9yhho'),
('the-order-2024-uk', 'a3219'),
('falling-in-love-in-niagara-uk', 'xylov'),
('falling-in-love-in-niagara-uk', 'uklbv'),
('armor-uk', 'kriminalne'),
('armor-uk', '9yhho'),
('armor-uk', 'q9wdt'),
('dear-beautiful-beloved-uk', 'mg36o'),
('how-to-be-normal-and-the-oddness-of-the-other-world-uk', 'a3219'),
('pulled-pork-uk', 'kriminalne'),
('pulled-pork-uk', 'uklbv'),
('peacock-2024-uk', 'a3219'),
('peacock-2024-uk', 'uklbv'),
('vikradenii', 'istorichne'),
('vikradenii', 'a3219'),
('absolution-uk', 'kriminalne'),
('absolution-uk', '9yhho'),
('absolution-uk', 'a3219'),
('absolution-uk', '6yl3z'),
('pokaz-iz-lekcieu-les-femmes-au-balcon-uk', 'hponb'),
('pokaz-iz-lekcieu-les-femmes-au-balcon-uk', 'uklbv'),
('pokaz-iz-lekcieu-les-femmes-au-balcon-uk', 'c065f'),
('kwity-ukrainy', 'mg36o'),
('pre-premiere-dwie-siostry-uk', 'vijskove'),
('pre-premiere-dwie-siostry-uk', 'a3219'),
('special-show-the-legend-of-ochi-uk', 'w2923'),
('special-show-the-legend-of-ochi-uk', 'hponb'),
('pre-premiere-until-dawn-2025-uk', 'c065f'),
('mission-impossible-dead-reckoning-part-one-uk', '9yhho'),
('mission-impossible-dead-reckoning-part-one-uk', 'w2923'),
('mission-impossible-dead-reckoning-part-one-uk', 'q9wdt'),
('silver-servers-uk', 'sportivne'),
('silver-servers-uk', 'mg36o'),
('the-great-escaper-uk', 'yiijd'),
('the-great-escaper-uk', '5a17z'),
('priputni-uk', 'roud-muvi'),
('priputni-uk', 'tragikomediya'),
('priputni-uk', '5a17z'),
('paris-13th-district-uk', 'erotichne'),
('paris-13th-district-uk', 'chorno-bile'),
('paris-13th-district-uk', '5a17z'),
('paris-13th-district-uk', 'xylov'),
('berlin-alexanderplatz-uk', 'kriminalne'),
('berlin-alexanderplatz-uk', 'nuar'),
('berlin-alexanderplatz-uk', 'socialne'),
('berlin-alexanderplatz-uk', '9yhho'),
('berlin-alexanderplatz-uk', 'a3kj3'),
('girl-picture-uk', 'a3kj3'),
('girl-picture-uk', 'xylov'),
('grosse-freiheit-uk', 'erotichne'),
('grosse-freiheit-uk', '5a17z');


